"""
Seed 50 accessibility POI markers across Ho Chi Minh City.
Safe to run multiple times (clears existing rows first).

Usage:
  cd backend
  python scripts/seed_points.py
"""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from datetime import datetime, timezone
from app.db.database import SessionLocal
from app.models.accessibility_point import AccessibilityPoint

POINTS = [
    # ── Hospitals ──────────────────────────────────────────────────────────────
    {
        "name": "Chợ Rẫy Hospital",
        "category": "hospital",
        "lat": 10.7551, "lng": 106.6685,
        "accessibility_score": 82,
        "address": "201B Nguyen Chi Thanh St, District 5",
        "description": "Major public hospital with wheelchair-accessible entrances and elevator access to all floors.",
        "features": ["Wheelchair entrance", "Elevator access", "Accessible parking", "Accessible toilets", "Wheelchair ramp at main gate"],
        "issues": ["Crowded ramps during peak hours", "Some side entrances lack ramps"],
        "verified": True, "has_ramp": True, "has_toilet": True, "has_parking": True, "has_elevator": True, "is_community_report": False,
    },
    {
        "name": "FV Hospital",
        "category": "hospital",
        "lat": 10.7282, "lng": 106.7228,
        "accessibility_score": 96,
        "address": "6 Nguyen Luong Bang St, District 7",
        "description": "International-standard hospital with full accessibility compliance throughout the facility.",
        "features": ["Fully accessible entrance", "Elevator", "Accessible parking bays", "Accessible toilets on every floor", "Wheelchair loan service", "Handrails throughout"],
        "issues": [],
        "verified": True, "has_ramp": True, "has_toilet": True, "has_parking": True, "has_elevator": True, "is_community_report": False,
    },
    {
        "name": "Children's Hospital 1",
        "category": "hospital",
        "lat": 10.7728, "lng": 106.6920,
        "accessibility_score": 70,
        "address": "341 Su Van Hanh St, District 10",
        "description": "Dedicated children's hospital with accessible main entrance, limited side access.",
        "features": ["Wheelchair entrance", "Elevator", "Accessible toilets"],
        "issues": ["Side entrance lacks ramp", "Parking area uneven surface"],
        "verified": True, "has_ramp": True, "has_toilet": True, "has_parking": False, "has_elevator": True, "is_community_report": False,
    },
    {
        "name": "Saigon General Hospital",
        "category": "hospital",
        "lat": 10.7728, "lng": 106.6975,
        "accessibility_score": 65,
        "address": "125 Le Loi St, District 1",
        "description": "Central district hospital with basic accessibility features.",
        "features": ["Wheelchair entrance", "Accessible toilets"],
        "issues": ["Elevator under maintenance", "Ramp slope is steep"],
        "verified": True, "has_ramp": True, "has_toilet": True, "has_parking": False, "has_elevator": False, "is_community_report": False,
    },
    {
        "name": "Columbia Asia Saigon International Clinic",
        "category": "hospital",
        "lat": 10.7935, "lng": 106.6988,
        "accessibility_score": 90,
        "address": "8 Alexandre De Rhodes St, District 1",
        "description": "Modern international clinic with excellent accessibility features.",
        "features": ["Fully accessible entrance", "Elevator", "Accessible toilets", "Accessible parking", "Smooth ramps"],
        "issues": [],
        "verified": True, "has_ramp": True, "has_toilet": True, "has_parking": True, "has_elevator": True, "is_community_report": False,
    },
    # ── Accessible Parking ─────────────────────────────────────────────────────
    {
        "name": "Vincom Center B Parking",
        "category": "accessible_parking",
        "lat": 10.7722, "lng": 106.7016,
        "accessibility_score": 92,
        "address": "72 Le Thanh Ton St, District 1",
        "description": "Underground parking with dedicated accessible bays near elevator.",
        "features": ["6 accessible bays", "Wide spaces", "Level floor", "Elevator to all floors"],
        "issues": [],
        "verified": True, "has_ramp": True, "has_toilet": True, "has_parking": True, "has_elevator": True, "is_community_report": False,
    },
    {
        "name": "Diamond Plaza Parking",
        "category": "accessible_parking",
        "lat": 10.7848, "lng": 106.7002,
        "accessibility_score": 88,
        "address": "34 Le Duan St, District 1",
        "description": "Multi-level parking with dedicated accessible spaces on ground floor.",
        "features": ["4 accessible bays on ground floor", "Elevator access", "Accessible toilets"],
        "issues": ["Ramp from street to parking has sharp turn"],
        "verified": True, "has_ramp": True, "has_toilet": True, "has_parking": True, "has_elevator": True, "is_community_report": False,
    },
    {
        "name": "Bitexco Financial Tower Parking",
        "category": "accessible_parking",
        "lat": 10.7718, "lng": 106.7047,
        "accessibility_score": 90,
        "address": "2 Hai Trieu St, District 1",
        "description": "Premium basement parking with accessible bays near lift lobby.",
        "features": ["8 accessible bays", "Smooth surfaces", "Elevator", "24/7 security"],
        "issues": [],
        "verified": True, "has_ramp": True, "has_toilet": False, "has_parking": True, "has_elevator": True, "is_community_report": False,
    },
    {
        "name": "Ben Thanh Market Street Parking",
        "category": "accessible_parking",
        "lat": 10.7722, "lng": 106.6983,
        "accessibility_score": 52,
        "address": "Le Loi St, District 1 (near Ben Thanh Market)",
        "description": "Street-side parking near Ben Thanh with limited accessible provisions.",
        "features": ["2 marked accessible bays"],
        "issues": ["Often occupied by non-disabled vehicles", "Uneven kerb"],
        "verified": False, "has_ramp": False, "has_toilet": False, "has_parking": True, "has_elevator": False, "is_community_report": False,
    },
    {
        "name": "Landmark 81 Basement Parking",
        "category": "accessible_parking",
        "lat": 10.7954, "lng": 106.7218,
        "accessibility_score": 96,
        "address": "720A Dien Bien Phu St, Binh Thanh District",
        "description": "State-of-the-art accessible parking in the city's tallest building.",
        "features": ["10 accessible bays", "Direct elevator access", "Smooth wide ramps", "Accessible toilets"],
        "issues": [],
        "verified": True, "has_ramp": True, "has_toilet": True, "has_parking": True, "has_elevator": True, "is_community_report": False,
    },
    # ── Accessible Toilets ─────────────────────────────────────────────────────
    {
        "name": "Nguyen Hue Walking Street Public Toilet",
        "category": "accessible_toilet",
        "lat": 10.7755, "lng": 106.7031,
        "accessibility_score": 78,
        "address": "Nguyen Hue Walking St, District 1",
        "description": "Modern public toilet with accessible cubicle and grab rails.",
        "features": ["Accessible cubicle", "Grab rails", "Wide door", "Level access"],
        "issues": ["Can be busy during events"],
        "verified": True, "has_ramp": True, "has_toilet": True, "has_parking": False, "has_elevator": False, "is_community_report": False,
    },
    {
        "name": "Tao Dan Park Accessible Toilet",
        "category": "accessible_toilet",
        "lat": 10.7770, "lng": 106.6898,
        "accessibility_score": 62,
        "address": "Tao Dan Park, District 1",
        "description": "Public toilet block in the park with accessible cubicle.",
        "features": ["Accessible cubicle", "Grab rails"],
        "issues": ["Path to toilet is uneven", "No automatic door"],
        "verified": True, "has_ramp": True, "has_toilet": True, "has_parking": False, "has_elevator": False, "is_community_report": False,
    },
    {
        "name": "Ben Thanh Market Toilet Block",
        "category": "accessible_toilet",
        "lat": 10.7730, "lng": 106.6980,
        "accessibility_score": 48,
        "address": "Inside Ben Thanh Market, District 1",
        "description": "Toilet facility inside the market with limited accessibility.",
        "features": ["Accessible cubicle available"],
        "issues": ["Narrow entrance corridor", "Steps at market entrance before toilet", "Often crowded"],
        "verified": False, "has_ramp": False, "has_toilet": True, "has_parking": False, "has_elevator": False, "is_community_report": False,
    },
    {
        "name": "Bitexco Tower Accessible Toilet",
        "category": "accessible_toilet",
        "lat": 10.7720, "lng": 106.7045,
        "accessibility_score": 92,
        "address": "2 Hai Trieu St, B1 Level, District 1",
        "description": "Premium accessible toilet on the basement level of Bitexco tower.",
        "features": ["Full accessible cubicle", "Automatic door", "Grab rails", "Emergency cord", "Baby changing"],
        "issues": [],
        "verified": True, "has_ramp": True, "has_toilet": True, "has_parking": True, "has_elevator": True, "is_community_report": False,
    },
    {
        "name": "War Remnants Museum Toilet",
        "category": "accessible_toilet",
        "lat": 10.7785, "lng": 106.6926,
        "accessibility_score": 70,
        "address": "28 Vo Van Tan St, District 3",
        "description": "Accessible toilet near the museum entrance for visitors.",
        "features": ["Accessible cubicle", "Grab rails", "Level access from main path"],
        "issues": ["Door can be heavy"],
        "verified": True, "has_ramp": True, "has_toilet": True, "has_parking": False, "has_elevator": False, "is_community_report": False,
    },
    # ── Wheelchair Ramps ───────────────────────────────────────────────────────
    {
        "name": "Nguyen Hue – Le Loi Curb Ramp",
        "category": "wheelchair_ramp",
        "lat": 10.7731, "lng": 106.7031,
        "accessibility_score": 88,
        "address": "Intersection of Nguyen Hue & Le Loi, District 1",
        "description": "Well-maintained curb cuts at all four corners of the intersection.",
        "features": ["Tactile paving", "Gentle slope", "All four corners have ramps"],
        "issues": [],
        "verified": True, "has_ramp": True, "has_toilet": False, "has_parking": False, "has_elevator": False, "is_community_report": False,
    },
    {
        "name": "Bitexco Tower Street Ramp",
        "category": "wheelchair_ramp",
        "lat": 10.7716, "lng": 106.7048,
        "accessibility_score": 94,
        "address": "2 Hai Trieu St, District 1",
        "description": "High-quality ramp from street level to tower entrance.",
        "features": ["Gentle gradient (1:20)", "Handrails both sides", "Anti-slip surface", "Tactile warning strip"],
        "issues": [],
        "verified": True, "has_ramp": True, "has_toilet": False, "has_parking": False, "has_elevator": False, "is_community_report": False,
    },
    {
        "name": "Reunification Palace Entrance Ramp",
        "category": "wheelchair_ramp",
        "lat": 10.7797, "lng": 106.6955,
        "accessibility_score": 74,
        "address": "135 Nam Ky Khoi Nghia St, District 1",
        "description": "Ramp at the main entrance of the historic Reunification Palace.",
        "features": ["Ramp present", "Handrail one side"],
        "issues": ["Slope slightly steeper than ideal", "No tactile paving"],
        "verified": True, "has_ramp": True, "has_toilet": True, "has_parking": True, "has_elevator": False, "is_community_report": False,
    },
    {
        "name": "Ben Thanh Market North Entrance Ramp",
        "category": "wheelchair_ramp",
        "lat": 10.7732, "lng": 106.6982,
        "accessibility_score": 60,
        "address": "North Gate, Ben Thanh Market, District 1",
        "description": "Ramped access at the north gate of Ben Thanh Market.",
        "features": ["Ramp available"],
        "issues": ["Steep gradient", "Surface can be slippery when wet", "Vendors sometimes block the ramp"],
        "verified": True, "has_ramp": True, "has_toilet": False, "has_parking": False, "has_elevator": False, "is_community_report": False,
    },
    {
        "name": "Diamond Plaza Ramp",
        "category": "wheelchair_ramp",
        "lat": 10.7846, "lng": 106.7005,
        "accessibility_score": 85,
        "address": "34 Le Duan St, District 1",
        "description": "Smooth ramp leading from street to Diamond Plaza main lobby.",
        "features": ["Gentle slope", "Handrails both sides", "Anti-slip surface"],
        "issues": [],
        "verified": True, "has_ramp": True, "has_toilet": False, "has_parking": False, "has_elevator": False, "is_community_report": False,
    },
    # ── Accessible Entrances ───────────────────────────────────────────────────
    {
        "name": "Bitexco Financial Tower",
        "category": "accessible_entrance",
        "lat": 10.7718, "lng": 106.7047,
        "accessibility_score": 95,
        "address": "2 Hai Trieu St, District 1",
        "description": "Fully accessible entrance with automatic doors, ramp, and elevator to all floors.",
        "features": ["Automatic sliding doors", "Level threshold", "Direct elevator access", "Accessible reception desk"],
        "issues": [],
        "verified": True, "has_ramp": True, "has_toilet": True, "has_parking": True, "has_elevator": True, "is_community_report": False,
    },
    {
        "name": "Caravelle Hotel",
        "category": "accessible_entrance",
        "lat": 10.7756, "lng": 106.7043,
        "accessibility_score": 92,
        "address": "19 Lam Son Square, District 1",
        "description": "Five-star hotel with fully accessible entrance and comprehensive accessibility features.",
        "features": ["Automatic doors", "Ramp from street", "Elevator", "Accessible rooms available", "Accessible toilets in lobby"],
        "issues": [],
        "verified": True, "has_ramp": True, "has_toilet": True, "has_parking": True, "has_elevator": True, "is_community_report": False,
    },
    {
        "name": "Saigon Opera House",
        "category": "accessible_entrance",
        "lat": 10.7769, "lng": 106.7043,
        "accessibility_score": 72,
        "address": "7 Lam Son Square, District 1",
        "description": "Historic opera house with accessible side entrance for wheelchair users.",
        "features": ["Accessible side entrance", "Elevator to seating levels", "Dedicated wheelchair spaces"],
        "issues": ["Main front steps have no ramp", "Accessible entrance not well-signposted"],
        "verified": True, "has_ramp": True, "has_toilet": True, "has_parking": False, "has_elevator": True, "is_community_report": False,
    },
    {
        "name": "HCMC Museum",
        "category": "accessible_entrance",
        "lat": 10.7764, "lng": 106.6966,
        "accessibility_score": 75,
        "address": "65 Ly Tu Trong St, District 1",
        "description": "City museum with ramped side entrance and accessible ground floor exhibits.",
        "features": ["Ramped entrance", "Accessible ground floor", "Accessible toilet"],
        "issues": ["Upper floors only accessible via stairs", "Ramp surface can be slippery"],
        "verified": True, "has_ramp": True, "has_toilet": True, "has_parking": False, "has_elevator": False, "is_community_report": False,
    },
    {
        "name": "Vincom Center A",
        "category": "accessible_entrance",
        "lat": 10.7731, "lng": 106.7016,
        "accessibility_score": 90,
        "address": "171 Dong Khoi St, District 1",
        "description": "Premium shopping center with fully accessible main entrance.",
        "features": ["Automatic doors", "Level entrance", "Elevator on all floors", "Accessible toilets", "Accessible parking"],
        "issues": [],
        "verified": True, "has_ramp": True, "has_toilet": True, "has_parking": True, "has_elevator": True, "is_community_report": False,
    },
    {
        "name": "Notre-Dame Cathedral Accessible Gate",
        "category": "accessible_entrance",
        "lat": 10.7797, "lng": 106.6993,
        "accessibility_score": 60,
        "address": "1 Cong Xa Paris, District 1",
        "description": "Accessible side gate to the cathedral grounds for wheelchair users.",
        "features": ["Side gate with level access", "Paved path to cathedral steps"],
        "issues": ["Interior has steps, no ramp inside", "Cobblestone area near entrance can be difficult"],
        "verified": True, "has_ramp": False, "has_toilet": False, "has_parking": False, "has_elevator": False, "is_community_report": False,
    },
    # ── Bus Stops ──────────────────────────────────────────────────────────────
    {
        "name": "Ben Thanh Bus Terminal",
        "category": "bus_stop",
        "lat": 10.7718, "lng": 106.6980,
        "accessibility_score": 65,
        "address": "Ben Thanh Bus Terminal, District 1",
        "description": "Major bus hub with partial accessibility provisions.",
        "features": ["Low-floor buses on some routes", "Paved waiting area"],
        "issues": ["No accessible toilets at terminal", "Some bays have kerb gaps", "Crowded during peak hours"],
        "verified": True, "has_ramp": True, "has_toilet": False, "has_parking": False, "has_elevator": False, "is_community_report": False,
    },
    {
        "name": "Le Loi / Pasteur Bus Stop",
        "category": "bus_stop",
        "lat": 10.7726, "lng": 106.6994,
        "accessibility_score": 52,
        "address": "Le Loi & Pasteur intersection, District 1",
        "description": "Standard bus stop with shelter but limited accessibility.",
        "features": ["Shelter available"],
        "issues": ["No kerb cut at stop", "Narrow footpath blocks wheelchair access", "Bus floor not level with kerb"],
        "verified": False, "has_ramp": False, "has_toilet": False, "has_parking": False, "has_elevator": False, "is_community_report": False,
    },
    {
        "name": "Ham Nghi / Nguyen Hue Bus Stop",
        "category": "bus_stop",
        "lat": 10.7712, "lng": 106.7024,
        "accessibility_score": 58,
        "address": "Ham Nghi & Nguyen Hue St, District 1",
        "description": "Bus stop near the financial district with basic accessibility.",
        "features": ["Flat paved area", "Shelter"],
        "issues": ["Step up to shelter", "Motorcycles frequently parked blocking access"],
        "verified": False, "has_ramp": False, "has_toilet": False, "has_parking": False, "has_elevator": False, "is_community_report": False,
    },
    {
        "name": "Dong Khoi / Le Loi Bus Stop",
        "category": "bus_stop",
        "lat": 10.7721, "lng": 106.7041,
        "accessibility_score": 62,
        "address": "Dong Khoi & Le Loi, District 1",
        "description": "Central bus stop with adequate space for wheelchair manoeuvring.",
        "features": ["Wide paved area", "Nearby kerb cut"],
        "issues": ["Bus boarding can be difficult without assistance"],
        "verified": False, "has_ramp": True, "has_toilet": False, "has_parking": False, "has_elevator": False, "is_community_report": False,
    },
    {
        "name": "District 3 Accessible Bus Stop",
        "category": "bus_stop",
        "lat": 10.7820, "lng": 106.6878,
        "accessibility_score": 55,
        "address": "Vo Thi Sau St, District 3",
        "description": "Bus stop with new kerb cuts as part of 2025 infrastructure upgrade.",
        "features": ["New kerb cut installed", "Wide footpath"],
        "issues": ["Shelter has step", "Surface uneven near stop"],
        "verified": True, "has_ramp": True, "has_toilet": False, "has_parking": False, "has_elevator": False, "is_community_report": False,
    },
    # ── Community Reports ──────────────────────────────────────────────────────
    {
        "name": "Blocked Sidewalk — Nguyen Hue North",
        "category": "community_report",
        "lat": 10.7760, "lng": 106.7031,
        "accessibility_score": 22,
        "address": "Nguyen Hue Walking St (North section), District 1",
        "description": "Construction material and scaffolding blocking the walking street ramp.",
        "features": [],
        "issues": ["Construction material blocking entire ramp", "No alternative accessible path marked"],
        "verified": False, "has_ramp": False, "has_toilet": False, "has_parking": False, "has_elevator": False, "is_community_report": True,
    },
    {
        "name": "Construction Barrier — Le Loi",
        "category": "community_report",
        "lat": 10.7721, "lng": 106.7010,
        "accessibility_score": 18,
        "address": "Le Loi St near Pasteur intersection, District 1",
        "description": "Ongoing construction project has removed accessible path for 200m stretch.",
        "features": [],
        "issues": ["Footpath completely removed", "Diversion route has steep unpaved slope", "No signage for wheelchair users"],
        "verified": True, "has_ramp": False, "has_toilet": False, "has_parking": False, "has_elevator": False, "is_community_report": True,
    },
    {
        "name": "No Ramps — Bui Vien Walking Street",
        "category": "community_report",
        "lat": 10.7647, "lng": 106.6978,
        "accessibility_score": 15,
        "address": "Bui Vien St, District 1",
        "description": "Entire street has no kerb cuts or ramps. Historic street vendors block remaining flat areas.",
        "features": [],
        "issues": ["No kerb cuts", "Street vendors block footpath", "Uneven cobblestones", "High noise level"],
        "verified": True, "has_ramp": False, "has_toilet": False, "has_parking": False, "has_elevator": False, "is_community_report": True,
    },
    {
        "name": "Parked Motorcycles — De Tham",
        "category": "community_report",
        "lat": 10.7660, "lng": 106.6960,
        "accessibility_score": 20,
        "address": "De Tham St, District 1",
        "description": "Sidewalk completely blocked by illegally parked motorcycles throughout the day.",
        "features": [],
        "issues": ["Motorcycles block entire footpath", "Wheelchair users forced onto road", "Recurring issue despite signs"],
        "verified": False, "has_ramp": False, "has_toilet": False, "has_parking": False, "has_elevator": False, "is_community_report": True,
    },
    {
        "name": "Flooded Footpath — Ham Nghi",
        "category": "community_report",
        "lat": 10.7712, "lng": 106.7055,
        "accessibility_score": 25,
        "address": "Ham Nghi St (East), District 1",
        "description": "Regular flooding after rain makes footpath impassable for wheelchair users.",
        "features": [],
        "issues": ["Flooding after moderate rain", "Drain grates have large gaps", "Can remain flooded for 1–2 hours"],
        "verified": False, "has_ramp": False, "has_toilet": False, "has_parking": False, "has_elevator": False, "is_community_report": True,
    },
    {
        "name": "Newly Accessible Route — Dong Khoi",
        "category": "community_report",
        "lat": 10.7743, "lng": 106.7043,
        "accessibility_score": 82,
        "address": "Dong Khoi St (central section), District 1",
        "description": "Community report: recent resurfacing and kerb cuts make this section newly accessible.",
        "features": ["New kerb cuts", "Smooth resurfaced footpath", "Widened pedestrian area"],
        "issues": [],
        "verified": False, "has_ramp": True, "has_toilet": False, "has_parking": False, "has_elevator": False, "is_community_report": True,
    },
    {
        "name": "Broken Curb Ramp — Tran Hung Dao",
        "category": "community_report",
        "lat": 10.7680, "lng": 106.7040,
        "accessibility_score": 18,
        "address": "Tran Hung Dao St near Nguyen Thi Nghia, District 1",
        "description": "Curb ramp has cracked and partially collapsed, creating a hazard.",
        "features": [],
        "issues": ["Cracked ramp surface", "Edge has sharp drop", "Reported to district council — no action yet"],
        "verified": True, "has_ramp": False, "has_toilet": False, "has_parking": False, "has_elevator": False, "is_community_report": True,
    },
    # ── Accessibility Issues ────────────────────────────────────────────────────
    {
        "name": "Missing Curb Cut — Pasteur St",
        "category": "accessibility_issue",
        "lat": 10.7745, "lng": 106.6994,
        "accessibility_score": 20,
        "address": "Pasteur St, District 1",
        "description": "No kerb cut at the southern end of Pasteur St forcing wheelchair users into traffic.",
        "features": [],
        "issues": ["No kerb cut at pedestrian crossing", "Kerb height approx 15 cm", "High traffic speed"],
        "verified": True, "has_ramp": False, "has_toilet": False, "has_parking": False, "has_elevator": False, "is_community_report": False,
    },
    {
        "name": "Broken Pavement — Pham Ngu Lao",
        "category": "accessibility_issue",
        "lat": 10.7660, "lng": 106.6966,
        "accessibility_score": 15,
        "address": "Pham Ngu Lao St, District 1",
        "description": "Severely broken pavement tiles create significant hazard for wheelchair users.",
        "features": [],
        "issues": ["Broken and lifted tiles", "Sections completely missing", "Deep puddles after rain"],
        "verified": True, "has_ramp": False, "has_toilet": False, "has_parking": False, "has_elevator": False, "is_community_report": False,
    },
    {
        "name": "Steep Slope — Nguyen Thai Hoc",
        "category": "accessibility_issue",
        "lat": 10.7693, "lng": 106.6970,
        "accessibility_score": 22,
        "address": "Nguyen Thai Hoc St near Tran Phu intersection, District 1",
        "description": "Road section with steep gradient and no handrails, extremely challenging for manual wheelchair users.",
        "features": [],
        "issues": ["Gradient approx 12% — too steep", "No handrails", "No alternative flat route"],
        "verified": False, "has_ramp": False, "has_toilet": False, "has_parking": False, "has_elevator": False, "is_community_report": False,
    },
    {
        "name": "Narrow Footpath — Hai Ba Trung",
        "category": "accessibility_issue",
        "lat": 10.7750, "lng": 106.7054,
        "accessibility_score": 28,
        "address": "Hai Ba Trung St, District 1",
        "description": "Footpath width only 60 cm — too narrow for most wheelchairs.",
        "features": [],
        "issues": ["Footpath width 60 cm (min required: 120 cm)", "Street vendors reduce usable width further", "Parked motorcycles block what remains"],
        "verified": True, "has_ramp": False, "has_toilet": False, "has_parking": False, "has_elevator": False, "is_community_report": False,
    },
    {
        "name": "Missing Handrails — Co Giang Overpass",
        "category": "accessibility_issue",
        "lat": 10.7669, "lng": 106.6995,
        "accessibility_score": 24,
        "address": "Co Giang St pedestrian overpass, District 1",
        "description": "Pedestrian overpass with ramp but missing handrail on one side, making it unsafe.",
        "features": ["Ramp present"],
        "issues": ["Missing handrail on right side of ramp", "Ramp surface worn and slippery"],
        "verified": False, "has_ramp": True, "has_toilet": False, "has_parking": False, "has_elevator": False, "is_community_report": False,
    },
    {
        "name": "Pothole — Vo Van Tan",
        "category": "accessibility_issue",
        "lat": 10.7700, "lng": 106.6980,
        "accessibility_score": 28,
        "address": "Vo Van Tan St, District 3",
        "description": "Large pothole on wheelchair accessible path creates fall hazard.",
        "features": [],
        "issues": ["Pothole 30 cm diameter, 8 cm deep", "In main pedestrian route", "Reported March 2026 — not repaired"],
        "verified": False, "has_ramp": False, "has_toilet": False, "has_parking": False, "has_elevator": False, "is_community_report": False,
    },
    {
        "name": "Blocked Accessible Entrance — District 3 Post Office",
        "category": "accessibility_issue",
        "lat": 10.7812, "lng": 106.6883,
        "accessibility_score": 18,
        "address": "5 Cong Truong Quoc Te, District 3",
        "description": "The designated accessible entrance is permanently blocked by motorbike parking.",
        "features": [],
        "issues": ["Accessible entrance blocked daily", "No enforcement of no-parking rule", "Main entrance has 5 steps — no ramp"],
        "verified": True, "has_ramp": False, "has_toilet": False, "has_parking": False, "has_elevator": False, "is_community_report": False,
    },
    {
        "name": "Drain Grate Hazard — Le Thanh Ton",
        "category": "accessibility_issue",
        "lat": 10.7750, "lng": 106.7020,
        "accessibility_score": 32,
        "address": "Le Thanh Ton St, District 1",
        "description": "Drain grates with gaps wide enough to trap wheelchair wheels.",
        "features": [],
        "issues": ["Grate gaps 4 cm wide — traps small caster wheels", "Covers 30 m of footpath", "Several near-miss incidents reported"],
        "verified": True, "has_ramp": False, "has_toilet": False, "has_parking": False, "has_elevator": False, "is_community_report": False,
    },
]


def run():
    db = SessionLocal()
    try:
        deleted = db.query(AccessibilityPoint).delete()
        print(f"Cleared {deleted} existing point(s).")

        for data in POINTS:
            point = AccessibilityPoint(**data)
            db.add(point)

        db.commit()
        print(f"Seeded {len(POINTS)} accessibility points.")
    finally:
        db.close()


if __name__ == "__main__":
    run()
