"""add photo_url

Revision ID: 87a4a7507aa3
Revises: 43634c6994e0
Create Date: 2026-06-27 23:21:25.623592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87a4a7507aa3'
down_revision: Union[str, Sequence[str], None] = '43634c6994e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accessibility_points', sa.Column('photo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accessibility_points', 'photo_url')
    # ### end Alembic commands ###
