"""create road_segments table

Revision ID: 88bb0f9572af
Revises: 
Create Date: 2026-06-27 21:14:23.721766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '88bb0f9572af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('road_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('sidewalk', sa.Boolean(), nullable=True),
    sa.Column('sidewalk_side', sa.String(), nullable=True),
    sa.Column('width_m', sa.Float(), nullable=True),
    sa.Column('surface', sa.String(), nullable=True),
    sa.Column('curb_ramp', sa.Boolean(), nullable=True),
    sa.Column('obstacles', sa.JSON(), nullable=True),
    sa.Column('stairs', sa.Boolean(), nullable=True),
    sa.Column('accessibility_score', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # GeoAlchemy2 creates the spatial index automatically on table creation
    op.create_index(op.f('ix_road_segments_id'), 'road_segments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_road_segments_id'), table_name='road_segments')
    # GeoAlchemy2 spatial index dropped automatically with the table
    op.drop_table('road_segments')
    # ### end Alembic commands ###
